name: Moodle Plugin CI checks

on: [push, pull_request]

jobs:
  moodle-plugin-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: mbstring, pgsql
          tools: phpunit

      - name: Deploy moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8

      - name: Install moodle-plugin-ci
        run: moodle-plugin-ci install -vvv --plugin ./plugin
        env:
          DB: 'pgsql'
          MOODLE_BRANCH: 'MOODLE_310_STABLE'
          IGNORE_PATHS: 'tests/fixtures/'

      - name: Run phplint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: Run phpcpd
        continue-on-error: true
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: Run phpmd
        continue-on-error: true
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: Run codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker --max-warnings 0

      - name: Run validate
        # AMOS has its own tables prefixed with 'amos' instead of 'local_amos' for legacy reasons.
        continue-on-error: true
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Run savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Run mustache
        # Some validation warnings are unavoidable as individual templates may not be fully valid HTML (e.g. table rows).
        continue-on-error: true
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Run grunt
        if: ${{ always() }}
        run: moodle-plugin-ci grunt --tasks=compile --max-lint-warnings 0

      - name: Run phpdoc
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc

      - name: Run AMOS phpunit tests
        if: ${{ always() }}
        # AMOS runs git as a part of unit tests.
        run: |
          git config --global user.name "Github Runner"
          git config --global user.email "github-runner@example.com"
          moodle-plugin-ci phpunit

      - name: Run related core phpunit tests
        if: ${{ always() }}
        run: |
          cd moodle
          vendor/bin/phpunit --fail-on-risky --disallow-test-output -v admin/tool/dataprivacy/tests/metadata_registry_test.php
          vendor/bin/phpunit --fail-on-risky --disallow-test-output -v privacy/tests/provider_test.php

      - name: Run behat
        if: ${{ always() }}
        run: moodle-plugin-ci behat --profile chrome
